export const TrademarkIncomingPagedata = [
  {
    id: 1,
    projectNo: 'P2024-001',
    caseCode: 'RD-2024-001',
    applicationNo: '202410000001.1',
    caseName: '智能网关系统',
    sourceType: '通知书',
    officialDocumentDate: '2024-01-15',
    notificationBrief: '受理通知',
    notificationCode: 'N001',
    internalCode: 'INT-001',
    documentSequenceNumber: 'SEQ-001',
    notificationName: '发明专利申请受理通知书',
    applicationDate: '2023-09-10',
    applicationType: '发明',
    priorityExamination: 'N',
    priorityLevel: null,
    preliminaryCase: 'Y',
    institutionNumber: 'A123',
    customerName: '华科技有限公司',
    status: '未处理',
    fileCategoryMajor: '专利',
    fileCategoryMinor: '发明',
    caseId: 100,
  },
  {
    id: 2,
    projectNo: 'P2024-002',
    caseCode: 'RD-2024-002',
    applicationNo: '202410000002.2',
    caseName: '新型传感器设计',
    sourceType: '通知书',
    officialDocumentDate: '2024-02-10',
    notificationBrief: '审查意见',
    notificationCode: 'N002',
    internalCode: 'INT-002',
    documentSequenceNumber: 'SEQ-002',
    notificationName: '审查意见通知书',
    applicationDate: '2023-10-05',
    applicationType: '实用新型',
    priorityExamination: 'N',
    priorityLevel: null,
    preliminaryCase: 'Y',
    institutionNumber: 'A124',
    customerName: '创新研究院',
    status: '处理中',
    fileCategoryMajor: '专利',
    fileCategoryMinor: '实用新型',
    caseId: 101,
  },
  {
    id: 3,
    projectNo: 'P2024-003',
    caseCode: 'RD-2024-003',
    applicationNo: '202410000003.3',
    caseName: '外观设计专利A',
    sourceType: '通知书',
    officialDocumentDate: '2024-03-05',
    notificationBrief: '授权通知',
    notificationCode: 'N003',
    internalCode: 'INT-003',
    documentSequenceNumber: 'SEQ-003',
    notificationName: '授权通知书',
    applicationDate: '2023-11-20',
    applicationType: '外观',
    priorityExamination: 'N',
    priorityLevel: null,
    preliminaryCase: 'N',
    institutionNumber: 'A125',
    customerName: '设计工作室',
    status: '已完成',
    fileCategoryMajor: '专利',
    fileCategoryMinor: '外观',
    caseId: 102,
  },
  {
    id: 4,
    projectNo: 'P2024-004',
    caseCode: 'RD-2024-004',
    applicationNo: '202410000004.4',
    caseName: '品牌商标注册',
    sourceType: '通知书',
    officialDocumentDate: '2024-03-20',
    notificationBrief: '受理通知',
    notificationCode: 'N004',
    internalCode: 'INT-004',
    documentSequenceNumber: 'SEQ-004',
    notificationName: '商标受理通知',
    applicationDate: '2023-12-01',
    applicationType: '商标',
    priorityExamination: 'N',
    priorityLevel: null,
    preliminaryCase: 'Y',
    institutionNumber: 'A123',
    customerName: '品牌管理公司',
    status: '未处理',
    fileCategoryMajor: '商标',
    fileCategoryMinor: '商标',
    caseId: 103,
  },
  {
    id: 5,
    projectNo: 'P2024-005',
    caseCode: 'RD-2024-005',
    applicationNo: '202410000005.5',
    caseName: '高效算法优化',
    sourceType: '通知书',
    officialDocumentDate: '2024-04-01',
    notificationBrief: '驳回决定',
    notificationCode: 'N005',
    internalCode: 'INT-005',
    documentSequenceNumber: 'SEQ-005',
    notificationName: '驳回决定书',
    applicationDate: '2024-01-15',
    applicationType: '发明',
    priorityExamination: 'Y',
    priorityLevel: '高',
    preliminaryCase: 'N',
    institutionNumber: 'A124',
    customerName: '技术股份公司',
    status: '已完成',
    fileCategoryMajor: '专利',
    fileCategoryMinor: '发明',
    caseId: 104,
  },
]
